[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Redirect root to index.html for better UX
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Handle 404s gracefully - return empty response for unknown country codes
[[redirects]]
  from = "/*"
  to = "/404.txt"
  status = 404